# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3s < Formula
  desc "Easy S3 select like searching in directories"
  homepage "https://github.com/koluku/s3s"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koluku/s3s/releases/download/v0.4.2/s3s_0.4.2_darwin_arm64.tar.gz"
      sha256 "3480d6233d22eea7b11dc9f5968c07f0291e75139274973d5a987fa86ded672e"

      def install
        bin.install "s3s"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koluku/s3s/releases/download/v0.4.2/s3s_0.4.2_darwin_amd64.tar.gz"
      sha256 "d98dc6ccfde397649dbe6104f3cabd0cd63737e977161a9ce719e660e2b7c07e"

      def install
        bin.install "s3s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koluku/s3s/releases/download/v0.4.2/s3s_0.4.2_linux_arm64.tar.gz"
      sha256 "284f81fc23d66bdff5a42c5991384afbf693adb32d7f07ae86100ad8b5696417"

      def install
        bin.install "s3s"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koluku/s3s/releases/download/v0.4.2/s3s_0.4.2_linux_amd64.tar.gz"
      sha256 "b97ba39633327b859d4e2f6850dfea87b54993e46e6c0e95002d08a02d3aa63e"

      def install
        bin.install "s3s"
      end
    end
  end
end
